<a href="https://colab.research.google.com/github/Saurabh-Datta/Fuel_Price_Predictor/blob/main/fuel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fuel Price Predictor

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv("https://raw.githubusercontent.com/Saurabh-Datta/Fuel_Price_Predictor/main/petrol.csv")

In [4]:
X = dataset.iloc[:, 0].values
y = dataset.iloc[:, 1:].values

In [5]:
print(X)

['April 19 2018' 'April 18 2018' 'April 17 2018' 'April 16 2018'
 'April 15 2018' 'April 14 2018' 'April 13 2018' 'April 12 2018'
 'April 11 2018' 'April 10 2018' 'April 09 2018' 'April 08 2018'
 'April 07 2018' 'April 06 2018' 'April 05 2018' 'April 04 2018'
 'April 03 2018' 'April 02 2018' 'April 01 2018' 'March 31 2018'
 'March 30 2018' 'March 29 2018' 'March 28 2018' 'March 27 2018'
 'March 26 2018' 'March 25 2018' 'March 24 2018' 'March 23 2018'
 'March 22 2018' 'March 21 2018' 'March 20 2018' 'March 19 2018'
 'March 18 2018' 'March 17 2018' 'March 16 2018' 'March 15 2018'
 'March 14 2018' 'March 13 2018' 'March 12 2018' 'March 11 2018'
 'March 10 2018' 'March 09 2018' 'March 08 2018' 'March 07 2018'
 'March 06 2018' 'March 05 2018' 'March 04 2018' 'March 03 2018'
 'March 02 2018' 'March 01 2018' 'February 28 2018' 'February 27 2018'
 'February 26 2018' 'February 25 2018' 'February 24 2018'
 'February 23 2018' 'February 22 2018' 'February 21 2018'
 'February 20 2018' 'February 19 

In [6]:
print(y)

[[74.07 76.77 81.92 76.84]
 [74.02 76.73 81.87 76.79]
 [74.02 76.73 81.87 76.79]
 ...
 [71.56 79.42 80.16 74.76]
 [71.51 79.36 80.11 74.71]
 [71.51 79.36 80.11 74.71]]


In [7]:
X.size

374

In [8]:
m = [0]*374

In [9]:
mo = [0]*374

In [10]:
i=0
while (i<374):
  if (X[i].find("January") != -1):
    m[i]=0
    mo[i]=1
  if (X[i].find("February") != -1):
    m[i]=31
    mo[i]=2
  if (X[i].find("March") != -1):
    m[i]=59
    mo[i]=3
  if (X[i].find("April") != -1):
    m[i]=90
    mo[i]=4
  if (X[i].find("May") != -1):
    m[i]=120
    mo[i]=5
  if (X[i].find("June") != -1):
    m[i]=151
    mo[i]=6
  if (X[i].find("July") != -1):
    m[i]=181
    mo[i]=7
  if (X[i].find("August") != -1):
    m[i]=212
    mo[i]=8
  if (X[i].find("September") != -1):
    m[i]=243
    mo[i]=9
  if (X[i].find("October") != -1):
    m[i]=273
    mo[i]=10
  if (X[i].find("November") != -1):
    m[i]=304
    mo[i]=11
  if (X[i].find("December") != -1):
    m[i]=334
    mo[i]=12
  i+=1

In [11]:
m

[90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 59,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 334,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 304,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,
 273,


In [12]:
ye = [0]*374

In [13]:
i = 0
while (i<374):
  ye[i]= (int(X[i][-4:])-2013)
  i+=1

In [14]:
ye

[5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,


In [22]:
i = 0
date = [0]*374
while (i<374):
  if (ye[i]==1):
    date[i] = 0
  if (ye[i]==2):
    date[i] = 365
  if (ye[i]==3):
    date[i] = 730
  if (ye[i]==4):
    date[i] = 1096
  if (ye[i]==5):
    date[i] = 1461
  date[i] += m[i]
  if (ye[i]==3 and mo[i]>2):
    date[i] +=1
  date[i] += int(X[i][-7:-5])
  i+=1

In [23]:
date[0]

1570

In [31]:
X = date

In [32]:
X[0]

1570

## Splitting the dataset into the Training set and Test set

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Random Forest Regression model on the whole dataset

In [36]:
X = np.array(X)

In [37]:
X.reshape(374,1)

array([[1570],
       [1569],
       [1568],
       [1567],
       [1566],
       [1565],
       [1564],
       [1563],
       [1562],
       [1561],
       [1560],
       [1559],
       [1558],
       [1557],
       [1556],
       [1555],
       [1554],
       [1553],
       [1552],
       [1551],
       [1550],
       [1549],
       [1548],
       [1547],
       [1546],
       [1545],
       [1544],
       [1543],
       [1542],
       [1541],
       [1540],
       [1539],
       [1538],
       [1537],
       [1536],
       [1535],
       [1534],
       [1533],
       [1532],
       [1531],
       [1530],
       [1529],
       [1528],
       [1527],
       [1526],
       [1525],
       [1524],
       [1523],
       [1522],
       [1521],
       [1520],
       [1519],
       [1518],
       [1517],
       [1516],
       [1515],
       [1514],
       [1513],
       [1512],
       [1511],
       [1510],
       [1509],
       [1508],
       [1507],
       [1506],
       [1505],
       [15

In [43]:
X= X.reshape(374,1)

In [45]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

## Predicting the Test set results

In [50]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)

In [51]:
y_pred

array([[69.19, 71.95, 77.03, 71.7 ],
       [63.47, 66.45, 74.72, 65.9 ],
       [67.78, 70.38, 76.49, 70.85],
       [70.51, 73.25, 79.62, 73.09],
       [70.42, 73.16, 79.53, 73.  ],
       [70.17, 72.92, 78.06, 72.74],
       [67.84, 70.63, 76.98, 70.28],
       [69.36, 72.12, 76.53, 71.88],
       [73.03, 75.72, 80.89, 75.75],
       [71.51, 74.26, 79.39, 74.15],
       [64.29, 67.09, 75.53, 66.77],
       [68.98, 71.75, 76.09, 71.49],
       [72.22, 74.93, 80.09, 74.89],
       [64.28, 67.68, 73.62, 66.75],
       [61.24, 68.73, 68.83, 64.06],
       [70.44, 73.18, 79.55, 73.02],
       [71.61, 74.35, 79.49, 74.26],
       [69.18, 71.94, 76.29, 71.69],
       [59.8 , 64.95, 66.18, 59.55],
       [69.26, 71.85, 75.6 , 71.03],
       [69.45, 72.21, 76.56, 71.97],
       [72.46, 75.19, 80.33, 75.15],
       [69.21, 71.96, 78.32, 71.71],
       [70.45, 73.2 , 79.56, 73.03],
       [67.24, 69.91, 73.6 , 67.49],
       [72.93, 75.63, 80.8 , 75.64],
       [70.34, 73.09, 79.45, 72.91],
 

In [52]:
y_test

array([[69.19, 71.95, 77.06, 71.7 ],
       [63.46, 66.45, 74.71, 65.9 ],
       [68.09, 70.68, 77.46, 71.17],
       [70.52, 73.26, 79.63, 73.1 ],
       [70.41, 73.15, 79.52, 72.99],
       [70.28, 73.02, 78.17, 72.85],
       [67.76, 70.55, 76.89, 70.19],
       [69.36, 72.12, 76.52, 71.88],
       [73.1 , 75.79, 80.96, 75.82],
       [71.53, 74.28, 79.41, 74.17],
       [63.99, 66.86, 75.23, 66.45],
       [69.07, 71.84, 76.18, 71.58],
       [72.07, 74.78, 79.94, 74.74],
       [64.28, 67.68, 73.61, 66.75],
       [66.29, 73.76, 74.12, 69.45],
       [70.43, 73.17, 79.54, 73.01],
       [71.52, 74.27, 79.4 , 74.16],
       [69.25, 72.01, 76.36, 71.77],
       [59.03, 64.87, 66.09, 59.45],
       [70.6 , 73.13, 76.91, 70.07],
       [69.41, 72.17, 76.52, 71.94],
       [72.47, 75.2 , 80.34, 75.16],
       [69.15, 71.92, 78.28, 71.66],
       [70.83, 73.57, 79.94, 73.43],
       [68.94, 71.5 , 75.27, 68.41],
       [72.92, 75.62, 80.79, 75.63],
       [70.38, 73.12, 79.48, 72.95],
 

## Evaluating the Model Performance

In [53]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9435022601511434